### ISSUE TITLE
Unallocated files despite proper id

### ISSUE THREAD

**Issue by PaulScotti** [lukassnoek/BidsConverter#3]
I am using dicom files, such as this:
https://puu.sh/Cg2XJ/ba41b73866.png

In my config.yml, I am filling out the fields like so: https://puu.sh/Cg311/2724a508f5.png

Unfortunately, bidsify always returns with all my dcm files being unallocated. I tried for several hours trying to figure out why, changing file names and id, but nothing seems to be helping.

**Comment by PaulScotti** [comment]
Here is my config.yml, converted to txt to allow me to attach it.
[config.txt](https://github.com/spinoza-rec/bidsify/files/2668777/config.txt)

**Comment by lukassnoek** [comment]
Hmm, interesting. Your config-file looks reasonable. Do your `.dcm` files actually get converted to nifti? If not, that it's probably the `dcm2niix` command failing (because I haven't configured it for Siemens/GE-style DICOMs properly, I think).

If the `.dcm` files do not get converted, could you send me an example `.dcm` file?

**Comment by PaulScotti** [comment]
Yes, I just get an unallocated folder with all my .dcm files. I emailed you an example .dcm file, thanks for taking a look.

**Comment by lukassnoek** [comment]
Thanks for emailing the example file! The issue was that I assumed DICOM files to be in the Philips format, which is slightly different from the Siemens format. I just pushed a (potential) fix to the master branch. The config file now supports the `mri_ext` value "dcm", which refers to Siemens DICOMs. If you change your config-file accordingly, the conversion should work.

That said, I noticed that your files did not contain any valid mappings. For example, your file named `ColorEncoder_1_15_00001.dcm` does not have any filetype associated with it. From the filename, bidsify cannot determine what filetype it is (e.g., `bold` or `T1w`). I've further specified this issue in the README.

To fix this issue, you should set the `mappings` correctly. Note that you can use glob patterns, e.g. `Color*[1,2]?`, in your mappings-settings.

Hope this helps!

**Comment by PaulScotti** [comment]
Thanks for taking the time to update things so that it can work with .dcm files! Perhaps I am still not using mappings correctly, but I am now getting .nii.gz files for each volume, rather than across volumes, for a run. For instance: https://puu.sh/Ci2la/cead4a3be3.png

I changed my config.yml to look like this: https://puu.sh/Ci2vx/6c7cfd2696.png
I also tried changing "bold: Color" to "bold: Color*[1,2]?" like you suggested, but that led to the same results.

**Comment by lukassnoek** [comment]
Sorry for the delay! Hmm, weird, are you using the latest version of `dcm2niix`?

**Comment by PaulScotti** [comment]
Yeah, I just made sure to update it and the same problem occurs...

**Comment by lukassnoek** [comment]
Okay, I've tried something completely different. I've added the feature that you can use `bidsify` using Docker. If you're familiar with Docker, you can try to use it to see whether the problem persists.

This is what you should do to use the Docker interface:
1. Pull the docker image: `docker pull lukassnoek/bidsify:0.3`
2. Get the latest version of `bidsify` from github and install
3. Run the same command as you did before (something like `bidsify -c /home/user/config.yml -d /home/user/data`) but now append the flag `-D` to it. This runs it with Docker. Note: you have to use absolute paths for your data and config file (so /home/user/config.yml and not config.yml).

Let me know if this works!

**Comment by PaulScotti** [comment]
Sorry for all this troubleshooting, but I attempted this method using docker and get:

> Unable to find image 'lukassnoek/bidsify:0.3.1' locally
> Error response from daemon: manifest for lukassnoek/bidsify:0.3.1 not found

**Comment by lukassnoek** [comment]
No worries! It's actually a very nice way to test whether the package works for datasets apart from my own :)

I actually didn't upload a new Docker version before (so bidsify:0.3.1 didn't exist yet), but I did so now. You should be able to pull it with the command

```
$ docker pull lukassnoek/bidsify:0.3.1
```

Let me know if this works!

**Comment by PaulScotti** [comment]
Haha well glad to help then. Docker does run now but I get a permission denied error:

> PermissionError: [Errno 13] Permission denied: '/bids/sub-01'

I tried running sudo before the command and still had the above error come up.

**Comment by lukassnoek** [comment]
What's the exact command you're running? (e.g., `bidsify -c /home/user/config.yml -d /home/user/data`)
And could it be that your data directory is read-only? Because when no output-directory is specified (by the `-o {your output directory}`), it will write the BIDS-files to the parent-directory of your data-directory (e.g., `/home/user/bids`). However, if that parent-directory (i.e., `/home/user`) is read-only, you'll get a permission error. 

What you could try is to specify the output-directory directly, and make sure you have write permission to this directory, e.g.:

```
bidsify -d /home/user/data -c /home/user/config.yml -o /home/user/directory_that_can_be_written_to -D
```

**Comment by PaulScotti** [comment]
It works, but I have the same problem as prior where I get .nii.gz files for each volume, rather than across volumes, for a run. I am wondering whether I can use bidsify without dcm2niix? E.g., I have a separate folder with already converted nifti files using [dicm2nii](https://www.mathworks.com/matlabcentral/fileexchange/42997-xiangruili-dicm2nii) with accompanied json files for BIDS.

**Comment by lukassnoek** [comment]
Hmm, I think you can! I added the possibility to bidsify niftis by adding the option "nifti" for as MRI-extension:

```yaml
options:
  mri_type: nifti
```

Given that there are already accompanying json-files, I think it could work. Let me know if it does (using the latest version of bidsify from Github)!

**Comment by lukassnoek** [comment]
Closing this issue due to inactivity.
