### ISSUE TITLE
Error using bidsify with multi-echo PAR/REC data

### ISSUE THREAD

**Issue by jsheunis** [lukassnoek/BidsConverter#7]
## Context

I have multi-echo fMRI data in PAR/REC format (v4.2), as well as a T1w image, that I would like to convert into BIDS format using bidsify. When I try to do this, I receive an error related to `dcm2niix`and the multi-echo PAR/REC to nifti conversion.

## Error and extra information
This is the error I receive running bidsify on my data (using a Mac and conda environment):
```
Error: Use dicm2nii or increase kMaxDTI4D to be more than 64260
  slices*grad*bval*cardiac*echo*dynamic*mix*label = 34*1*1*1*3*630*1*1
Found 630.000 dyns (21420 slices) for file <file>.PAR, but expected 210 dyns (7140 slices); going to try to fix it by removing slices from the PAR header ...
```
The interesting thing is that when I run dcm2niix on this data directly, the conversion to multi-echo nifti data works fine.

## Questions
Should I be setting this `kMaxDTI4D to be more than 64260`? Have you seen this issue before?

## Comments
Thanks for a great tool! I look forward to using it more.

**Comment by lukassnoek** [comment]
Ah, interesting! Never used it on multiecho data, which is causing the `Found 630.000 dyns (21420 slices) ...` message (which shouldn't happen). This can be fixed quite easily. Could you perhaps send me the (anonymized) ".PAR" header? 

The error `Use dicm2nii or ...` might be caused by the specific `dcm2niix` version. Are you using the Docker option in `bidsify`? And which version of `dcm2niix` are you using when you use it on your data directly?

**Comment by jsheunis** [comment]
Thanks, Lukas.

I get this output when running dcm2niix:
```
Chris Rorden's dcm2niiX version v1.0.20190410  Clang9.0.0 (64-bit MacOS)
```
I'm not using Docker. I have a conda environment set up with bidsify installed via pip. The par file is attached:

[testPAR_ME.PAR.zip](https://github.com/NILAB-UvA/bidsify/files/3703068/testPAR_ME.PAR.zip)

**Comment by lukassnoek** [comment]
I *think* I fixed it such that it should work with multiecho data. Could you install `bidsify` from source and try again? (using e.g. `pip install git+https://github.com/NILAB-UvA/bidsify.git`)

If not, let me know!

**Comment by jsheunis** [comment]
Thanks! This works, i.e. the single PAR/REC is now converted into a multi-echo nifti dataset (one .nii file for each of the 3 echoes), although another issue has surfaced. Most converted files are in the `unallocated` folder after `bidsify` has finished running. It looks like it's an issue with there not being a unique key per file anymore (if I'm not doing something else wrong).

The standard output from `dcm2niix` (if the `-f` option for the output filename is not set) will be something like:
```
testPAR_ME_<exam-date-and-series-nr>_e1.json
testPAR_ME_<exam-date-and-series-nr>_e1.nii
testPAR_ME_<exam-date-and-series-nr>_e2.json
testPAR_ME_<exam-date-and-series-nr>_e2.nii
testPAR_ME_<exam-date-and-series-nr>_e3.json
testPAR_ME_<exam-date-and-series-nr>_e3.nii
```
This would be for a single run, which might not be the only multi-echo run in the session/dataset. Thus, if I already have various `id` values in my `func` section in the `config` file in order to separately identify my different runs (e.g. `motor`, `emotion`, or `nback`), how would I further identify each echo in order to get to the naming convention of [BIDS](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fmri-task-information):

```
sub-<label>[_ses-<label>]_task-<label>[_acq-<label>][_ce-<label>][_dir-<label>][_rec-<label>][_run-<index>][_echo-<index>]_<contrast_label>.nii[.gz]
sub-<label>[_ses-<label>]_task-<label>[_acq-<label>][_ce-<label>][_dir-<label>][_rec-<label>][_run-<index>][_echo-<index>]_sbref.nii[.gz]

e.g.
sub-01_task-cuedSGT_run-1_echo-1_bold.nii.gz
```

This is what part of my config looks like at the moment:
```
func:
    rest:
        id: rest
        task: rest
        run: 1

    motor-task:
        id: motor
        task: motor
        run: 1

    emotion-task:
        id: emotion
        task: emotion
        run: 1
```
What do you think is a sensible solution/approach? For a quick fix I could of course do the dcm2niix conversion prior to running `bidsify`, and use converted+renamed nifti files together with an updated config to recognise the unique run-and-echo combinations during conversion to BIDS. But it seems like something more elegant would be possible within `bidsify`.

**Comment by lukassnoek** [comment]
Ah, shoot, that actually complicates matters. I think I have an idea to fix this. I would actually need a complete (multiecho) PAR/REC to test this. Could you send this to me as well?

**Comment by jsheunis** [comment]
[Here's a link](https://osf.io/g2qt7/) to a full resting state multi-echo fMRI dataset in PAR/REC format.

**Comment by lukassnoek** [comment]
Thanks! I just pushed some changes that should make multiecho conversion possible. (It does so by appending `*echo-x` to each file, but only when "number of echoes" in the PAR file is > 1). Let me know if it works! (it's not yet on pip, only on the master branch)

**Comment by jsheunis** [comment]
It doesn't seem to work on my side. I still get the same results where most `_e(x)` files that are output from `dcm2niix` are thrown in the unallocated folder.

I'm pretty sure I ran the latest version of `bidsify`. I did this in two ways:
- 1: `pip install git+https://github.com/NILAB-UvA/bidsify.git@master`
- 2: cloning the repo and running `python setup.py develop`

Both gave the same results.

Do the changes influence how the config file should be set up? Mine is still the same as specified above. Do I have to add more levels for all of the echoes?

**Comment by lukassnoek** [comment]
Hmm, weird. I just retested it in a new environment, and it seems to work. The fact that only `_e(x)` suggests that an old version is used. Could you uninstall bidsify (`pip uninstall bidsify`) and reinstall from master? (the command `pip install git+https://github.com/NILAB-UvA/bidsify.git@master` should work.)

Sorry for the hassle. Let me know if it works!

**Comment by jsheunis** [comment]
It works! Looks like uninstall and reinstall helped. Thanks a lot Lukas!

**Comment by lukassnoek** [comment]
Great! Glad I could help.
